### ISSUE TITLE
DESAIN

### ISSUE THREAD

**Issue by rizkyyusfian** [rizkyyusfian/lelangonline#1]
Desain masih belum jadi

**Comment by rizky1481** [comment]
Otw Buat

**Comment by geralele** [comment]
ayok garap bareng

**Comment by rizkyyusfian** [comment]
Desain **HOME** DONE

Yang belum selesai :
- login
- register
- add
- detail

**Comment by roby-firmansyah** [comment]
siap

**Comment by rizkyyusfian** [comment]
**Update Info Desain**

yang belum selesai :

- detail
