### ISSUE TITLE
Pembuatan Program

### ISSUE THREAD

**Issue by rizkyyusfian** [rizkyyusfian/lelangonline#3]
Yang harus dibuat :

- **login** dan proses
- **register** dan proses
- **home** untuk menampilkan list barang
- **add** untuk menambah barang
- **detail** untuk melihat info barang dan bid

**Comment by rizkyyusfian** [comment]
**login** - DONE
**register** - DONE
**home** - DONE
**add** - DONE

**Comment by geralele** [comment]
perhatikan dedlen ya ges

**Comment by roby-firmansyah** [comment]
detail sudah gan

**Comment by rizkyyusfian** [comment]
**Update** - 11/10/2020

**login**- DONE
**register** - DONE
**home** - DONE
**add** - DONE
**Detail** - DONE
