### ISSUE TITLE
Testing 1.0

### ISSUE THREAD

**Issue by rizkyyusfian** [rizkyyusfian/lelangonline#8]
Tolong semua di coba aplikasinya untuk bug check dan error check

**Comment by roby-firmansyah** [comment]
oke siap gan

**Comment by rizkyyusfian** [comment]
@rizky1481 @geralele @160418105

**Comment by geralele** [comment]
asiap

**Comment by rizkyyusfian** [comment]
ada dapet error ato nemu bug?

**Comment by geralele** [comment]
nanti kita diskusiin di msteam meets aja , skrg testing secara mandiri dulu

**Comment by rizkyyusfian** [comment]
lupa update issue, Testing 1 aman jadi tidak perlu melakukan Testing 2
